services:
  thought-to-image-simulation-api:
    container_name: thought-to-image-simulation-api
    image: evdev3/thought-to-image-simulation-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: unless-stopped
    env_file:
      - .env